### ISSUE TITLE
Impossible to sync photos

### ISSUE THREAD

**Issue by ManuCart** [danchal/flickrsync#2]
````
$ flickrsync sync
Do you want to sync the local file system with Flickr [Y/n] Y
Searching Flickr since the last upload date <1970-01-01 01:00:01>. This could take a long time
No deleted / undeleted photos found
No new photos found on Flickr since the last upload date
No files found in this directory </media/hdd/photos>
No unmatched Flickr photos found
No matched Flickr photos found
Selected <0> photos for upload to Flickr
No photos to upload
Uploaded: passed<0>, failed<0>
finished
````
Don't know why but possible my photos are not sort like you
For me : /media/hdd/photos/2007/2007-01-01 abcdefghj/2007.0001.JPEG
may be the JPEG is not correct too.

**Comment by danchal** [comment]
Yes, you are correct, only jpg, png, gif files were being searched for.
I have now added [jpeg](https://github.com/danchal/flickrsync/commit/8af88fa0b6b7ccbf255843a5033b464cb37e9cea) to the list.

**Comment by ManuCart** [comment]
Great!, it's working, now I'm waiting for 35000 photos
